### ISSUE TITLE
I want to learn about career opportunities as a committed contributor with Polywrap

### ISSUE THREAD

**Issue by evanjacobs** [polywrap/landing-page#100]

**Comment by rihp** [comment]
- [ ] Add Jobs link to the footer
![image](https://user-images.githubusercontent.com/12145726/158618513-83cf14df-9969-40c7-a222-2bde4d7c9746.png)

**Comment by evanjacobs** [comment]
@kev-ngo has been researching DAO tools for managing contributor on-boarding

**Comment by kev-ngo** [comment]
Still exploring options.  Met with the sales teams for:
- [FreshTeam](https://www.freshworks.com/hrms/)
- [Ashby](https://app.ashbyhq.com/access)

Ashby (founded 2019) in particular seems like a "DAO-friendly" option.  It allows you to create job postings, send them to multiple sites, and give view-only access to the platform for other DAO members.

Thus, all DAO members can see job applicants, the stage they're at in the interview process, any comments/ratings on them, etc.

Their pricing model is not so great.  It's based on headcount, which includes contractors.  Looking to see if I can negotiate this.

**Comment by kev-ngo** [comment]
Landed on Ashby as a hiring platform.

Will get a spending proposal up for this and integrate into our landing page within the next 1-2 weeks.

**Comment by kev-ngo** [comment]
Paid for Ashby.  They are setting it up now.  Will post proposal to reimburse myself.

**Comment by rihp** [comment]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/12145726/169615977-29dd4400-0292-4c7d-a530-d24eaf3fd69d.png">
this was added recently!
