### ISSUE TITLE
Create new Monaco syntax Highlighting that also works for the polywrap hub

### ISSUE THREAD

**Issue by rihp** [polywrap/landing-page#105]

**Comment by daoadvocate** [comment]
testing integration @rihp

**Comment by rihp** [comment]
This is what it currently looks like with no highlighting 
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/12145726/161837757-0aa21bc5-92f3-4f1e-92c7-00d7b561f2fd.png">

**Comment by rihp** [comment]
This is directly tied to https://github.com/polywrap/landing-page/issues/90

This is the current progress https://github.com/polywrap/landing-page/issues/105#issuecomment-1089256061

**Comment by rihp** [comment]
closing this as it's not necessary in the current implementation
