### ISSUE TITLE
Adapt the old hub component to cycle through the applications

### ISSUE THREAD

**Issue by evanjacobs** [polywrap/landing-page#129]

**Comment by dOrgJelli** [comment]
Should be completed by this PR: https://github.com/polywrap/landing-page/pull/136

**Comment by rihp** [comment]
This is already implemented in the `apps-showcase` branch (picture below)
However, the way it's currently implemented has dependency on the CMS.

![Image](https://user-images.githubusercontent.com/12145726/181064565-08156666-4482-4a4c-a472-62c7403710ca.png)

**Comment by rihp** [comment]
![Image](https://user-images.githubusercontent.com/12145726/181065232-d94ee9ab-7648-44ef-be7f-64e9c99d5beb.png)

**Comment by rihp** [comment]
Closing this as it's working in #136
