### ISSUE TITLE
Bug: Applications hero shows uniswap demo twice

### ISSUE THREAD

**Issue by rihp** [polywrap/landing-page#140]
- [ ] very subtle but should be fixed; This component shows the following sequence

Uniswap v2 -> Polyfolio -> Univ2 -> Univ2 again -> Polyfolio -> univ2 -> univ2 again ...
https://github.com/polywrap/landing-page/pull/136/files#diff-809e2d2b9e62a4b454a310424b29e7aea79cc51a19faeecd5444b1ca9414f8f6

- [x] Also, the featured wrappers should be managed from the CMS by turning the featured parameter on/off, not by hardcoding it as we did [here](https://github.com/polywrap/landing-page/pull/136/files#diff-809e2d2b9e62a4b454a310424b29e7aea79cc51a19faeecd5444b1ca9414f8f6R130-R134)

**Comment by dOrgJelli** [comment]
Closing as this issue relates to the old v1 landing page.
