### ISSUE TITLE
I want to go to a landing page that explains what Polywrap is and how I can use it

### ISSUE THREAD

**Issue by rihp** [polywrap/landing-page#89]
worth reviewing our sections and content, for example, we aren't detailing the registry or we can evaluate if the current descriptions need some different tone/examples

ALPHA:
- [x] #96
- [x] Review that all copy is shown appropriately on the site
- [x] One final review for all grammar and copy before closing this issue

Probably not Alpha:
- [ ]~~The website should mention the registry~~
- [x] #97
- [x] #99

**Comment by rihp** [comment]
This will be all implemented in issue https://github.com/polywrap/landing-page/issues/91

**Comment by rihp** [comment]
This is the task @QKiwi

https://github.com/orgs/polywrap/projects/6/views/1?filterQuery=label%3A%22story%22+milestone%3A%22alpha%22+rihp

**Comment by QKiwi** [comment]
hi #try

**Comment by QKiwi** [comment]
Edited the webcontent and wrote more about the 6 Next-Gen SDKs for Web3 except for composable, did not know what to add there!

**Comment by rihp** [comment]
Here is a preview of the Web Content  that we have on the contenful CMS so far. We already have a lot of comprehensive descriptions to finish up all the components necessary for this issue.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/12145726/165386694-f687342e-7294-4d89-96b7-6464837751d6.png">

**Comment by rihp** [comment]
Once #132  is merged to master, we´ll assign 2 knowledgeable contributors to review the copy to make sure it covers expectations
