### ISSUE TITLE
I want to go to a landing page that explains what Polywrap is and how I can use it

### ISSUE THREAD

**Issue by evanjacobs** [polywrap/landing-page#93]

**Comment by evanjacobs** [comment]
Acceptance criteria:

- [ ] Landing page contains succinct description of Polywrap
- [ ] Landing page has links to documentation

**Comment by rihp** [comment]
since the avg session is 48 seconds the text should be readable within this timeframe

<img width="274" alt="image" src="https://user-images.githubusercontent.com/12145726/156562364-45ca3518-cc81-4479-8718-a5891c2a7de3.png">

**Comment by evanjacobs** [comment]
This seems to be a duplicate of #89. Closing this issue in favor of that one.
