### ISSUE TITLE
Integrate Contentful as a Headless CMS service

### ISSUE THREAD

**Issue by rihp** [polywrap/landing-page#94]
Acceptance Criteria.
- [x] #103
- [x] #107
- [x] #108
- [x] #109
- [x] #110

**Comment by rihp** [comment]
Using contentful for the first time. Most of the content has been already uploaded to the platform.
I started developing the integration in the [contentful-dev branch](https://github.com/polywrap/landing-page/tree/contentful-dev) and am currently stuck at querying the API through POST.

I'm receiving this error after sending the POST query:
` "Query cannot be executed. The request does not include a query neither in the body nor in the query string"`


[This is the section of the code](https://github.com/polywrap/landing-page/blob/72871af464b6975cc23b8969525ef50b9fa66f5b/src/App.tsx#L38-L74) that prepares the headers/body and for the API request.


```typescript
  console.log("Hello world! this is my query");

  const cmsQuery = `{
    webContent(id:"6DWrAojZUdPcTSDXGip5PN") {
      title
    }
  }`;
  console.log(cmsQuery);


  const [content, setContent] = useState(null);

  useEffect(() => {
    window
      .fetch(process.env.REACT_APP_CMS_SITE as string, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": process.env.REACT_APP_CMS_TOKEN as string,
        },
        body: JSON.stringify({ cmsQuery }),
      })

      .then((response) => response.json())
      .then(({ data, errors }) => {
        if (errors) {
          console.log("There was an error with the query:");
          console.error(errors);
        }
        console.log("This is the data:", data);
        console.log(content);
        //setContent(data.webContent.items[0]);
      });
  }, []);
  ```

**Comment by rihp** [comment]
- [ ] Another thing to consider, is if this should be implemented in the main `/App.tsx` file, or in separate components.

**Comment by rihp** [comment]
the hero, demo and hub sections have been implemented. 🔌

for testimonials, partners and benefits additinonal handiwork is needed as the content structures are different

**Comment by rihp** [comment]
this is already integrated

**Comment by rihp** [comment]
reopening till this PR gets merged into master 
https://github.com/polywrap/landing-page/pull/134

**Comment by dOrgJelli** [comment]
Closing this as it has been reverted.
