### ISSUE TITLE
The website should mention the polyfolio

### ISSUE THREAD

**Issue by rihp** [polywrap/landing-page#97]
This one is probably covered by #91 

___Acceptance criteria___
- [x] Fetch all the necessary data from the CMS
- [x] Up to date description and screenshot
- [ ] A web3 newbie should be able to understand wtf is this
- [ ] A skilled web3 dev can check the code quickly and understand why this is better than the traditional approach by zerion/zapper

**Comment by evanjacobs** [comment]
@rihp We don't have a specific user story around Polyfolio for Alpha. Should we remove this task from the Alpha milestone?

**Comment by rihp** [comment]
Agreed, just that we would have only 1 app to showcase though (if we remove hub and polyfolio)

**Comment by rihp** [comment]
I´ll leave this issue open, but close the reference to this and alpha, so we can remember this can be added in the future

**Comment by rihp** [comment]
added with #146
